# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62450c9cffc2844b552d077642cb5da82e7d56d52c972d0c16a2552abcb120c226e1924d491a50c499dfb2459d035f78e2973ffbda542ea0eeed7e0a774de7eb

test:
  secret_key_base: 7775fd6e9ce4940c8816180d06449488d5545c5a9b0317beffc276835647fe06b9e557d7af015672b6c38edbad63e529231247d63fb921e8ddcad40f86552845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
